<?php
/*------------------------
 * Author: J.O. Pormento
 * Date Created: 02-07-2014
------------------------*/

$this->widget('bootstrap.widgets.TbGridView', array(
        'type'=>'striped bordered condensed',
        'dataProvider' => $dataProvider,
        'enablePagination' => true,
        'template'=>"{items}",
        'columns' => array(
                        array('name'=>'MemberName',
                              'header'=>'Member Name',
                              'type'=>'raw',
                              'value'=>'CHtml::encode($data["member_name"])',
                              'htmlOptions' => array('style' => 'text-align:center'),    
                        ), 
                        array('name'=>'Level',
                            'header'=>'Level',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["level_no"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'LoanAmount',
                            'header'=>'Loan Amount',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["loan_amount"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'DateCreated',
                            'header'=>'Date Created',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["date_created"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'DateApproved',
                            'header'=>'Date Approved',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["date_approved"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'ApprovedBy',
                            'header'=>'Approved By',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["approved_by"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
//                        array('name'=>'Email',
//                            'header'=>'Email',
//                            'type'=>'raw',
//                            'value'=>'CHtml::encode($data["email"])',
//                            'htmlOptions' => array('style' => 'text-align:center'),    
//                        ),
//                        array('name'=>'Action',
//                            'header'=>'',
//                            'type'=>'raw',
//                            'value'=>'CHtml::link("Update", array("members/update", "id"=>$data["member_id"]))',
//                            'htmlOptions' => array('style' => 'text-align:center; width: 5%;'),    
//                        ),
//                        array('name'=>'Action2',
//                            'header'=>'',
//                            'type'=>'raw',
//                            'value'=>'CHtml::link("Terminate", array("members/terminate", "id"=>$data["member_id"]))',
//                            'htmlOptions' => array('style' => 'text-align:center; width: 5%;'),    
//                        ),
//                        array(
//                            'class'=>'bootstrap.widgets.TbButtonColumn',
//                            'template'=>'{update} {delete}',
//                            'htmlOptions'=>array('style'=>'width: 50px'),
//                                                 'viewButtonUrl'=>null,
//                                                 'updateButtonUrl'=>'Yii::app()->createUrl("members/update", array("id"=>$data["member_id"]))',
//                                                 'deleteButtonUrl'=>null,
//                        ),
        )
        ));
?>
